import { defineConfig } from "vitest/config"
import react from "@vitejs/plugin-react"

export default defineConfig({
  plugins: [react()],
  resolve: { tsconfigPaths: true },
  test: {
    pool: "vmThreads",
    environment: "jsdom",
    env: {
      // Test encryption key — 32 bytes hex, used only in tests
      ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000001",
    },
    setupFiles: ["./test/setup.tsx"],
    include: ["test/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      include: [
        // lib — pure logic, all 100% enforced below
        "lib/ai-gateway.ts",
        "lib/api/session.ts",
        "lib/capture.ts",
        "lib/care.ts",
        "lib/care-grouping.ts",
        "lib/env.ts",
        "lib/invites.ts",
        "lib/lifewalk-parse.ts",
        "lib/lifewalk-prompt.ts",
        "lib/offer.ts",
        "lib/offer-data.ts",
        "lib/push.ts",
        "lib/seed-care-plan.ts",
        "lib/supabase/server-service.ts",
        "lib/tasks.ts",
        "lib/thing-persistence.ts",
        "lib/things-service.ts",
        // api routes — 100% enforced below
        "app/api/account/route.ts",
        "app/api/ai-key/route.ts",
        "app/api/capture/voice/route.ts",
        "app/api/care-groups/report/route.ts",
        "app/api/care-plans/[id]/route.ts",
        "app/api/entities/route.ts",
        "app/api/integrations/route.ts",
        "app/api/lifewalk/route.ts",
        "app/api/offer/route.ts",
        "app/api/push/subscribe/route.ts",
        "app/api/steps/[id]/event/route.ts",
        "app/api/things/route.ts",
        "app/api/things/[id]/route.ts",
        "app/api/things/[id]/prepend-lookup/route.ts",
        "app/api/things/[id]/done/route.ts",
        "app/api/things/[id]/start/route.ts",
        "app/auth/confirm/route.ts",
        // components — reported but no threshold
        "app/auth/page.tsx",
        "app/components/AddTaskButton.tsx",
        "app/components/AppShell.tsx",
        "app/components/CareGroupCard.tsx",
        "app/components/CarePlanEditor.tsx",
        "app/components/OfferCard.tsx",
        "app/components/Spinner.tsx",
        "app/components/capture/CaptureContext.tsx",
        "app/components/capture/CaptureModal.tsx",
        "app/components/capture/EntityCaptureFlow.tsx",
        "app/components/capture/SwipeableTaskRow.tsx",
        "app/components/capture/TaskCaptureFlow.tsx",
        "app/components/offer/FamiliarityScreen.tsx",
        "app/components/offer/FocusScreen.tsx",
        "app/components/offer/OfferScreen.tsx",
        "app/components/offer/SettingsScreen.tsx",
        "app/components/offer/useOfferCardState.ts",
      ],
      thresholds: {
        // 100% enforced on lib + api routes only
        "lib/**": { lines: 100, functions: 100, branches: 100, statements: 100 },
        "app/api/**": { lines: 100, functions: 100, branches: 100, statements: 100 },
        "app/auth/confirm/route.ts": { lines: 100, functions: 100, branches: 100, statements: 100 },
      },
    },
  },
})
