import { defineConfig } from "vitest/config"
import react from "@vitejs/plugin-react"
import tsconfigPaths from "vite-tsconfig-paths"

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./test/setup.tsx"],
    include: ["test/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      all: true,
      include: [
        "lib/api/session.ts",
        "lib/capture.ts",
        "lib/care.ts",
        "lib/care-grouping.ts",
        "lib/env.ts",
        "lib/lifewalk-parse.ts",
        "lib/lifewalk-prompt.ts",
        "lib/offer.ts",
        "lib/offer-data.ts",
        "lib/push.ts",
        "lib/recurrence.ts",
        "lib/seed-care-plan.ts",
        "lib/supabase/server-service.ts",
        "lib/tasks.ts",
        "lib/thing-persistence.ts",
        "lib/things-service.ts",
        "app/api/capture/voice/route.ts",
        "app/api/care-groups/report/route.ts",
        "app/api/care-plans/[id]/route.ts",
        "app/api/entities/route.ts",
        "app/api/lifewalk/route.ts",
        "app/api/offer/route.ts",
        "app/api/push/subscribe/route.ts",
        "app/api/steps/[id]/event/route.ts",
        "app/api/things/route.ts",
        "app/api/things/[id]/route.ts",
        "app/api/things/[id]/breakdown/route.ts",
        "app/api/things/[id]/done/route.ts",
        "app/api/things/[id]/start/route.ts",
        "app/auth/confirm/route.ts",
        "app/auth/page.tsx",
        "app/components/AddTaskButton.tsx",
        "app/components/AppShell.tsx",
        "app/components/CareGroupCard.tsx",
        "app/components/CarePlanEditor.tsx",
        "app/components/OfferCard.tsx",
        "app/components/Spinner.tsx",
        "app/components/capture/CaptureContext.tsx",
        "app/components/capture/CaptureModal.tsx",
        "app/components/capture/EntityCaptureFlow.tsx",
        "app/components/capture/SwipeableTaskRow.tsx",
        "app/components/capture/TaskCaptureFlow.tsx",
        "app/components/offer/FocusScreen.tsx",
        "app/components/offer/OfferScreen.tsx",
        "app/components/offer/SettingsScreen.tsx",
        "app/components/offer/useOfferCardState.ts",
      ],
      thresholds: {
        lines: 100,
        functions: 100,
        branches: 100,
        statements: 100,
      },
    },
  },
})
